spring.application.name=delivery-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=postgres
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost/orders

spring.jpa.hibernate.ddl-auto=update

spring.kafka.consumer.group-id=delivery-service-group
spring.kafka.bootstrap-servers=localhost:9092

server.port=8082

payment-service.base-url=http://localhost:8081

order-paid-topic=orders.events
delivery-assigned-topic=delivery.events

